### ISSUE TITLE
Create option to define temporary file path

### ISSUE THREAD

**Issue by schlaepferp** [sib-swiss/sendcrypt#10]
Dear Sir or madam,

To me it would have helped if you would allow the definition of the path where temporary files are saved. It seems that currently this path is by default /tmp but can not be changed. Is this correct?

Cheers,
Pascal

**Comment by dterumalai** [comment]
Hi Pascal, I imagine that you are talking about the CLI and not the GUI. You can find the CLI repository here: https://gitlab.sib.swiss/clinbio/sendcrypt/sendcrypt-cli.

Regarding your point, you can define the `TMPDIR` env variable before calling the CLI to modify the path (https://gitlab.sib.swiss/clinbio/sendcrypt/sendcrypt-cli/-/blob/main/sendcrypt?ref_type=heads#L24).
